// Code generated by go-swagger; DO NOT EDIT.

// Package handler API Telegram bot
//
//  Schemes:
//    http
//  Host: *
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package handler
