// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostSendOKCode is the HTTP code returned for type PostSendOK
const PostSendOKCode int = 200

/*PostSendOK Success

swagger:response postSendOK
*/
type PostSendOK struct {
}

// NewPostSendOK creates PostSendOK with default headers values
func NewPostSendOK() *PostSendOK {

	return &PostSendOK{}
}

// WriteResponse to the client
func (o *PostSendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostSendBadRequestCode is the HTTP code returned for type PostSendBadRequest
const PostSendBadRequestCode int = 400

/*PostSendBadRequest Bad request

swagger:response postSendBadRequest
*/
type PostSendBadRequest struct {
}

// NewPostSendBadRequest creates PostSendBadRequest with default headers values
func NewPostSendBadRequest() *PostSendBadRequest {

	return &PostSendBadRequest{}
}

// WriteResponse to the client
func (o *PostSendBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostSendInternalServerErrorCode is the HTTP code returned for type PostSendInternalServerError
const PostSendInternalServerErrorCode int = 500

/*PostSendInternalServerError Internal Server Error

swagger:response postSendInternalServerError
*/
type PostSendInternalServerError struct {
}

// NewPostSendInternalServerError creates PostSendInternalServerError with default headers values
func NewPostSendInternalServerError() *PostSendInternalServerError {

	return &PostSendInternalServerError{}
}

// WriteResponse to the client
func (o *PostSendInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
