swagger: "2.0"
info:
  version: "1.0.0"
  title: "API Telegram bot"
host: "*"
schemes :
- "http" 
paths:
  /send:
    post:
      summary: "Send message to all subscribers"
      parameters:
        - in: query
          name: msg
          description: "This message will be send all subscribers"
          required: true
          type: string
      responses:
        "200":
          description: "Success"
        "400":
          description: "Bad request"
        "500":
          description: "Internal Server Error"        